In [50]:
#wich model should i use ?

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()
import pandas as pd

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [19]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [21]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.94999999999999996

In [22]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.37592592592592594

In [23]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.97222222222222221

In [ ]:
#we compqre the score of the different model on one test sample
#we need to test it on different test sample to decide wich model is the best

In [77]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=9) #split into 3 fold
kf

KFold(n_splits=9, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print (train_index, test_index)
    
#divide the list in three fold with different train and test set

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, X_train, X_test, y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)


In [27]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

0.9115191986644408

In [28]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.4273789649415693

In [74]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=9)
#divide each of the classification categorie uniformly (better than Kfold)


In [78]:
score_l=[]
score_svm=[]
score_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    
#hard way but we can make it easy with cross value matter
    



In [79]:
score_l


[0.915,
 0.95,
 0.93,
 0.925,
 0.965,
 0.98,
 0.9447236180904522,
 0.8944723618090452,
 0.9246231155778895]

In [80]:
score_svm

[0.425,
 0.56,
 0.43,
 0.39,
 0.46,
 0.415,
 0.46733668341708545,
 0.45226130653266333,
 0.39195979899497485]

In [81]:
score_rf

[0.915,
 0.97,
 0.91,
 0.925,
 0.955,
 0.97,
 0.9597989949748744,
 0.964824120603015,
 0.9095477386934674]

In [75]:
from sklearn.model_selection import cross_val_score

In [86]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [33]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [47]:
np.mean(cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target))

0.9309752686107924

In [48]:
#exercice
from sklearn.datasets import load_iris
iris = load_iris()

In [59]:
df=pd.DataFrame(iris.data)
df.rename(columns={0:'sepal length (cm)',1:'sepal width (cm)',2:'petal length (cm)',3:'petal width (cm)'},inplace=True)
df.head()
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [64]:
np.mean(cross_val_score(RandomForestClassifier(n_estimators=800),iris.data,iris.target))

0.960375816993464

In [83]:
np.mean(cross_val_score(LogisticRegression(),iris.data,iris.target))

0.9468954248366014

In [85]:
(cross_val_score(SVC(),iris.data,iris.target))

array([0.98039216, 0.96078431, 0.97916667])